/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HolyGrail;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void nonserialTest(){
        int[] arr = {1,3,5,7,9};
        assertTrue(App.sumOfShots(arr,1,3,0) == 11);
    }

    @Test
    public void invalidTest(){
        int[] arr = {1,3,5,7,9};
        assertTrue(App.sumOfShots(arr,-1,0,45) == 1);
    }

    @Test
    public void nullTest(){
        assertTrue(App.sumOfShots(null,3,4,5) == 0);
    }

    @Test
    public void emptyArrayTest(){
        int[] arr = {};
        assertTrue(App.sumOfShots(arr,0,4,99) == 0);
    }
}
