/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HolyGrail;

public class App {
    
    public static int sumOfShots(int[] board,int attempt1, int attempt2, int attempt3) {
        if(board == null)
            return 0;

        int sum  = 0, size = board.length;
        int[] attemptArr = {attempt1,attempt2,attempt3};
        for(int i=0;i<3;i++)
            if(attemptArr[i]>=0 && attemptArr[i]<size)
                sum += board[attemptArr[i]];
        return sum;
    }
}
